# 4.8: Grouping Data & Aggregating Variables

1. Importing Data Frames and loading libraries

In [4]:
#1. Importing Data Frames and loading libraries

In [6]:
## Importing Data: 

import pandas as pd
import numpy as np
import os

path = r'C:\Users\cmfag\OneDrive\Desktop\Data Analyst Specialist\Achievement 4\4.3_orders_products\02 Data\Prepared Data'

In [8]:
#importing df_ords_prods_merge


df_ords_prods_merge = pd.read_pickle(os.path.join(path, 'df_ords_prods_merge.pkl'))

df_ords_prods_merge.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,Unnamed: 0,product_name,aisle_id,department_id,prices,merge_check,day_label,busiest_day,busiest_period_of_day
0,2539329,1,prior,1,2,8,NaN,196,1,0,195.0,Soda,77.0,7.0,9.0,both,Regularly busy,Regularly busy,Fewest orders
1,2539329,1,prior,1,2,8,NaN,14084,2,0,14084.0,Organic Unsweetened Vanilla Almond Milk,91.0,16.0,12.5,both,Regularly busy,Regularly busy,Fewest orders
2,2539329,1,prior,1,2,8,NaN,12427,3,0,12427.0,Original Beef Jerky,23.0,19.0,4.4,both,Regularly busy,Regularly busy,Fewest orders
3,2539329,1,prior,1,2,8,NaN,26088,4,0,26089.0,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Regularly busy,Regularly busy,Fewest orders
4,2539329,1,prior,1,2,8,NaN,26405,5,0,26406.0,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,both,Regularly busy,Regularly busy,Fewest orders

2 Grouping Data

In [13]:
#Creatin a subset

df = df_ords_prods_merge[:1000000]

In [15]:
df.shape

(1000000, 19)

In [17]:
df.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,Unnamed: 0,product_name,aisle_id,department_id,prices,merge_check,day_label,busiest_day,busiest_period_of_day
0,2539329,1,prior,1,2,8,NaN,196,1,0,195.0,Soda,77.0,7.0,9.0,both,Regularly busy,Regularly busy,Fewest orders
1,2539329,1,prior,1,2,8,NaN,14084,2,0,14084.0,Organic Unsweetened Vanilla Almond Milk,91.0,16.0,12.5,both,Regularly busy,Regularly busy,Fewest orders
2,2539329,1,prior,1,2,8,NaN,12427,3,0,12427.0,Original Beef Jerky,23.0,19.0,4.4,both,Regularly busy,Regularly busy,Fewest orders
3,2539329,1,prior,1,2,8,NaN,26088,4,0,26089.0,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Regularly busy,Regularly busy,Fewest orders
4,2539329,1,prior,1,2,8,NaN,26405,5,0,26406.0,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,both,Regularly busy,Regularly busy,Fewest orders

3 Grouping Data with pandas

In [20]:
df.groupby('product_name')

4 Aggregating Data with agg()

4.1 Performing a Single Aggregation

In [23]:
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1.0              14.792915
2.0              17.091743
3.0              17.919589
4.0              17.891973
5.0              15.214270
6.0              15.382228
7.0              17.699986
8.0              16.485269
9.0              15.965921
10.0             20.091818
11.0             16.485395
12.0             15.615845
13.0             16.485052
14.0             17.523474
15.0             15.690354
16.0             18.014342
17.0             16.155822
18.0             19.606536
19.0             17.630236
20.0             17.138204
21.0             21.996844

In [25]:
# Aggregation without using the agg() function

df.groupby('department_id')['order_number'].mean()

department_id
1.0     14.792915
2.0     17.091743
3.0     17.919589
4.0     17.891973
5.0     15.214270
6.0     15.382228
7.0     17.699986
8.0     16.485269
9.0     15.965921
10.0    20.091818
11.0    16.485395
12.0    15.615845
13.0    16.485052
14.0    17.523474
15.0    15.690354
16.0    18.014342
17.0    16.155822
18.0    19.606536
19.0    17.630236
20.0    17.138204
21.0    21.996844
Name: order_number, dtype: float64

4.2 Performing Multiple Aggregations

In [27]:
df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
1.0              14.792915   1  99
2.0              17.091743   1  98
3.0              17.919589   1  99
4.0              17.891973   1  99
5.0              15.214270   1  99
6.0              15.382228   1  99
7.0              17.699986   1  99
8.0              16.485269   1  91
9.0              15.965921   1  99
10.0             20.091818   1  99
11.0             16.485395   1  99
12.0             15.615845   1  99
13.0             16.485052   1  99
14.0             17.523474   1  99
15.0             15.690354   1  99
16.0             18.014342   1  99
17.0             16.155822   1  99
18.0             19.606536   1  99
19.0             17.630236   1  99
20.0             17.138204   1  99
21.0             21.996844   1  97

5 Aggregating Data with transform()

In [31]:
df_ords_prods_merge['max_order'] = df_ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

C:\Users\cmfag\AppData\Local\Temp\ipykernel_13016\136815596.py:1: FutureWarning: The provided callable <function max at 0x000001AFEE34C4A0> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df_ords_prods_merge['max_order'] = df_ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

In [33]:
df_ords_prods_merge.head(15)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,Unnamed: 0,product_name,aisle_id,department_id,prices,merge_check,day_label,busiest_day,busiest_period_of_day,max_order
0,2539329,1,prior,1,2,8,NaN,196,1,0,195.0,Soda,77.0,7.0,9.0,both,Regularly busy,Regularly busy,Fewest orders,10
1,2539329,1,prior,1,2,8,NaN,14084,2,0,14084.0,Organic Unsweetened Vanilla Almond Milk,91.0,16.0,12.5,both,Regularly busy,Regularly busy,Fewest orders,10
2,2539329,1,prior,1,2,8,NaN,12427,3,0,12427.0,Original Beef Jerky,23.0,19.0,4.4,both,Regularly busy,Regularly busy,Fewest orders,10
3,2539329,1,prior,1,2,8,NaN,26088,4,0,26089.0,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Regularly busy,Regularly busy,Fewest orders,10
4,2539329,1,prior,1,2,8,NaN,26405,5,0,26406.0,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,both,Regularly busy,Regularly busy,Fewest orders,10
5,2398795,1,prior,2,3,7,15.0,196,1,1,195.0,Soda,77.0,7.0,9.0,both,Regularly busy,Regularly busy,Fewest orders,10
6,2398795,1,prior,2,3,7,15.0,10258,2,0,10258.0,Pistachios,117.0,19.0,3.0,both,Regularly busy,Regularly busy,Fewest orders,10
7,2398795,1,prior,2,3,7,15.0,12427,3,1,12427.0,Original Beef Jerky,23.0,19.0,4.4,both,Regularly busy,Regularly busy,Fewest orders,10
8,2398795,1,prior,2,3,7,15.0,13176,4,0,13176.0,Bag of Organic Bananas,24.0,4.0,10.3,both,Regularly busy,Regularly busy,Fewest orders,10
9,2398795,1,prior,2,3,7,15.0,26088,5,1,26089.0,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Regularly busy,Regularly busy,Fewest orders,10
10,2398795,1,prior,2,3,7,15.0,13032,6,0,13032.0,Cinnamon Toast Crunch,121.0,14.0,4.0,both,Regularly busy,Regularly busy,Fewest orders,10
11,473747,1,prior,3,3,12,21.0,196,1,1,195.0,Soda,77.0,7.0,9.0,both,Regularly busy,Regularly busy,Fewest orders,10
12,473747,1,prior,3,3,12,21.0,12427,2,1,12427.0,Original Beef Jerky,23.0,19.0,4.4,both,Regularly busy,Regularly busy,Fewest orders,10
13,473747,1,prior,3,3,12,21.0,10258,3,1,10258.0,Pistachios,117.0,19.0,3.0,both,Regularly busy,Regularly busy,Fewest orders,10
14,473747,1,prior,3,3,12,21.0,25133,4,0,25134.0,Organic String Cheese,21.0,16.0,8.6,both,Regularly busy,Regularly busy,Fewest orders,10

In [37]:
df_ords_prods_merge.head(100)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,Unnamed: 0,product_name,aisle_id,department_id,prices,merge_check,day_label,busiest_day,busiest_period_of_day,max_order
0,2539329,1,prior,1,2,8,NaN,196,1,0,195.0,Soda,77.0,7.0,9.0,both,Regularly busy,Regularly busy,Fewest orders,10
1,2539329,1,prior,1,2,8,NaN,14084,2,0,14084.0,Organic Unsweetened Vanilla Almond Milk,91.0,16.0,12.5,both,Regularly busy,Regularly busy,Fewest orders,10
2,2539329,1,prior,1,2,8,NaN,12427,3,0,12427.0,Original Beef Jerky,23.0,19.0,4.4,both,Regularly busy,Regularly busy,Fewest orders,10
3,2539329,1,prior,1,2,8,NaN,26088,4,0,26089.0,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Regularly busy,Regularly busy,Fewest orders,10
4,2539329,1,prior,1,2,8,NaN,26405,5,0,26406.0,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,both,Regularly busy,Regularly busy,Fewest orders,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,738281,2,prior,4,2,10,8.0,21150,13,0,21151.0,Fire Grilled Steak Bowl,38.0,1.0,5.9,both,Regularly busy,Regularly busy,Fewest orders,14
96,1673511,2,prior,5,3,11,8.0,47144,1,0,47148.0,Unsweetened Original Almond Breeze Almond Milk,91.0,16.0,14.0,both,Regularly busy,Regularly busy,Fewest orders,14
97,1673511,2,prior,5,3,11,8.0,5322,2,0,5322.0,Gluten Free Dark Chocolate Chunk Chewy with a ...,3.0,19.0,2.9,both,Regularly busy,Regularly busy,Fewest orders,14
98,1673511,2,prior,5,3,11,8.0,17224,3,0,17224.0,Oats & Honey Gluten Free Granola,3.0,19.0,1.6,both,Regularly busy,Regularly busy,Fewest orders,14
99,1673511,2,prior,5,3,11,8.0,38656,4,0,38660.0,Gluten Free Peanut Butter Dark Chocolate Chewy...,3.0,19.0,3.4,both,Regularly busy,Regularly busy,Fewest orders,14

In [39]:
pd.options.display.max_rows = None

In [41]:
df_ords_prods_merge.head(100)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,Unnamed: 0,product_name,aisle_id,department_id,prices,merge_check,day_label,busiest_day,busiest_period_of_day,max_order
0,2539329,1,prior,1,2,8,NaN,196,1,0,195.0,Soda,77.0,7.0,9.0,both,Regularly busy,Regularly busy,Fewest orders,10
1,2539329,1,prior,1,2,8,NaN,14084,2,0,14084.0,Organic Unsweetened Vanilla Almond Milk,91.0,16.0,12.5,both,Regularly busy,Regularly busy,Fewest orders,10
2,2539329,1,prior,1,2,8,NaN,12427,3,0,12427.0,Original Beef Jerky,23.0,19.0,4.4,both,Regularly busy,Regularly busy,Fewest orders,10
3,2539329,1,prior,1,2,8,NaN,26088,4,0,26089.0,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Regularly busy,Regularly busy,Fewest orders,10
4,2539329,1,prior,1,2,8,NaN,26405,5,0,26406.0,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,both,Regularly busy,Regularly busy,Fewest orders,10
5,2398795,1,prior,2,3,7,15.0,196,1,1,195.0,Soda,77.0,7.0,9.0,both,Regularly busy,Regularly busy,Fewest orders,10
6,2398795,1,prior,2,3,7,15.0,10258,2,0,10258.0,Pistachios,117.0,19.0,3.0,both,Regularly busy,Regularly busy,Fewest orders,10
7,2398795,1,prior,2,3,7,15.0,12427,3,1,12427.0,Original Beef Jerky,23.0,19.0,4.4,both,Regularly busy,Regularly busy,Fewest orders,10
8,2398795,1,prior,2,3,7,15.0,13176,4,0,13176.0,Bag of Organic Bananas,24.0,4.0,10.3,both,Regularly busy,Regularly busy,Fewest orders,10
9,2398795,1,prior,2,3,7,15.0,26088,5,1,26089.0,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Regularly busy,Regularly busy,Fewest orders,10
10,2398795,1,prior,2,3,7,15.0,13032,6,0,13032.0,Cinnamon Toast Crunch,121.0,14.0,4.0,both,Regularly busy,Regularly busy,Fewest orders,10
11,473747,1,prior,3,3,12,21.0,196,1,1,195.0,Soda,77.0,7.0,9.0,both,Regularly busy,Regularly busy,Fewest orders,10
12,473747,1,prior,3,3,12,21.0,12427,2,1,12427.0,Original Beef Jerky,23.0,19.0,4.4,both,Regularly busy,Regularly busy,Fewest orders,10
13,473747,1,prior,3,3,12,21.0,10258,3,1,10258.0,Pistachios,117.0,19.0,3.0,both,Regularly busy,Regularly busy,Fewest orders,10
14,473747,1,prior,3,3,12,21.0,25133,4,0,25134.0,Organic String Cheese,21.0,16.0,8.6,both,Regularly busy,Regularly busy,Fewest orders,10
15,473747,1,prior,3,3,12,21.0,30450,5,0,30452.0,Creamy Almond Butter,88.0,13.0,3.2,both,Regularly busy,Regularly busy,Fewest orders,10
16,2254736,1,prior,4,4,7,29.0,196,1,1,195.0,Soda,77.0,7.0,9.0,both,Least busy,Least busy,Fewest orders,10
17,2254736,1,prior,4,4,7,29.0,12427,2,1,12427.0,Original Beef Jerky,23.0,19.0,4.4,both,Least busy,Least busy,Fewest orders,10
18,2254736,1,prior,4,4,7,29.0,10258,3,1,10258.0,Pistachios,117.0,19.0,3.0,both,Least busy,Least busy,Fewest orders,10
19,2254736,1,prior,4,4,7,29.0,25133,4,1,25134.0,Organic String Cheese,21.0,16.0,8.6,both,Least busy,Least busy,Fewest orders,10
20,2254736,1,prior,4,4,7,29.0,26405,5,1,26406.0,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,both,Least busy,Least busy,Fewest orders,10
21,431534,1,prior,5,4,15,28.0,196,1,1,195.0,Soda,77.0,7.0,9.0,both,Least busy,Least busy,Fewest orders,10
22,431534,1,prior,5,4,15,28.0,12427,2,1,12427.0,Original Beef Jerky,23.0,19.0,4.4,both,Least busy,Least busy,Fewest orders,10
23,431534,1,prior,5,4,15,28.0,10258,3,1,10258.0,Pistachios,117.0,19.0,3.0,both,Least busy,Least busy,Fewest orders,10
24,431534,1,prior,5,4,15,28.0,25133,4,1,25134.0,Organic String Cheese,21.0,16.0,8.6,both,Least busy,Least busy,Fewest orders,10
25,431534,1,prior,5,4,15,28.0,10326,5,0,10326.0,Organic Fuji Apples,24.0,4.0,2.7,both,Least busy,Least busy,Fewest orders,10
26,431534,1,prior,5,4,15,28.0,17122,6,0,17122.0,Honeycrisp Apples,24.0,4.0,14.0,both,Least busy,Least busy,Fewest orders,10
27,431534,1,prior,5,4,15,28.0,41787,7,0,41791.0,Bartlett Pears,24.0,4.0,5.0,both,Least busy,Least busy,Fewest orders,10
28,431534,1,prior,5,4,15,28.0,13176,8,1,13176.0,Bag of Organic Bananas,24.0,4.0,10.3,both,Least busy,Least busy,Fewest orders,10
29,3367565,1,prior,6,2,7,19.0,196,1,1,195.0,Soda,77.0,7.0,9.0,both,Regularly busy,Regularly busy,Fewest orders,10
30,3367565,1,prior,6,2,7,19.0,12427,2,1,12427.0,Original Beef Jerky,23.0,19.0,4.4,both,Regularly busy,Regularly busy,Fewest orders,10
31,3367565,1,prior,6,2,7,19.0,10258,3,1,10258.0,Pistachios,117.0,19.0,3.0,both,Regularly busy,Regularly busy,Fewest orders,10
32,3367565,1,prior,6,2,7,19.0,25133,4,1,25134.0,Organic String Cheese,21.0,16.0,8.6,both,Regularly busy,Regularly busy,Fewest orders,10
33,550135,1,prior,7,1,9,20.0,196,1,1,195.0,Soda,77.0,7.0,9.0,both,Regularly busy,Regularly busy,Fewest orders,10
34,550135,1,prior,7,1,9,20.0,10258,2,1,10258.0,Pistachios,117.0,19.0,3.0,both,Regularly busy,Regularly busy,Fewest orders,10
35,550135,1,prior,7,1,9,20.0,12427,3,1,12427.0,Original Beef Jerky,23.0,19.0,4.4,both,Regularly busy,Regularly busy,Fewest orders,10
36,550135,1,prior,7,1,9,20.0,25133,4,1,25134.0,Organic String Cheese,21.0,16.0,8.6,both,Regularly busy,Regularly busy,Fewest orders,10
37,550135,1,prior,7,1,9,20.0,13032,5,1,13032.0,Cinnamon Toast Crunch,121.0,14.0,4.0,both,Regularly busy,Regularly busy,Fewest orders,10
38,3108588,1,prior,8,1,14,14.0,12427,1,1,12427.0,Original Beef Jerky,23.0,19.0,4.4,both,Regularly busy,Regularly busy,Fewest orders,10
39,3108588,1,prior,8,1,14,14.0,196,2,1,195.0,Soda,77.0,7.0,9.0,both,Regularly busy,Regularly busy,Fewest orders,10
40,3108588,1,prior,8,1,14,14.0,10258,3,1,10258.0,Pistachios,117.0,19.0,3.0,both,Regularly busy,Regularly busy,Fewest orders,10
41,3108588,1,prior,8,1,14,14.0,25133,4,1,25134.0,Organic String Cheese,21.0,16.0,8.6,both,Regularly busy,Regularly busy,Fewest orders,10
42,3108588,1,prior,8,1,14,14.0,46149,5,0,46153.0,Zero Calorie Cola,77.0,7.0,13.4,both,Regularly busy,Regularly busy,Fewest orders,10
43,3108588,1,prior,8,1,14,14.0,49235,6,0,49239.0,Organic Half & Half,53.0,16.0,1.8,both,Regularly busy,Regularly busy,Fewest orders,10
44,2295261,1,prior,9,1,16,0.0,49235,1,1,49239.0,Organic Half & Half,53.0,16.0,1.8,both,Regularly busy,Regularly busy,Fewest orders,10
45,2295261,1,prior,9,1,16,0.0,46149,2,1,46153.0,Zero Calorie Cola,77.0,7.0,13.4,both,Regularly busy,Regularly busy,Fewest orders,10
46,2295261,1,prior,9,1,16,0.0,25133,3,1,25134.0,Organic String Cheese,21.0,16.0,8.6,both,Regularly busy,Regularly busy,Fewest orders,10
47,2295261,1,prior,9,1,16,0.0,196,4,1,195.0,Soda,77.0,7.0,9.0,both,Regularly busy,Regularly busy,Fewest orders,10
48,2295261,1,prior,9,1,16,0.0,10258,5,1,10258.0,Pistachios,117.0,19.0,3.0,both,Regularly busy,Regularly busy,Fewest orders,10
49,2295261,1,prior,9,1,16,0.0,12427,6,1,12427.0,Original Beef Jerky,23.0,19.0,4.4,both,Regularly busy,Regularly busy,Fewest orders,10
50,2550362,1,prior,10,4,8,30.0,196,1,1,195.0,Soda,77.0,7.0,9.0,both,Least busy,Least busy,Fewest orders,10
51,2550362,1,prior,10,4,8,30.0,46149,2,1,46153.0,Zero Calorie Cola,77.0,7.0,13.4,both,Least busy,Least busy,Fewest orders,10
52,2550362,1,prior,10,4,8,30.0,39657,3,0,39661.0,Milk Chocolate Almonds,45.0,19.0,6.8,both,Least busy,Least busy,Fewest orders,10
53,2550362,1,prior,10,4,8,30.0,38928,4,0,38932.0,0% Greek Strained Yogurt,120.0,16.0,12.6,both,Least busy,Least busy,Fewest orders,10
54,2550362,1,prior,10,4,8,30.0,25133,5,1,25134.0,Organic String Cheese,21.0,16.0,8.6,both,Least busy,Least busy,Fewest orders,10
55,2550362,1,prior,10,4,8,30.0,10258,6,1,10258.0,Pistachios,117.0,19.0,3.0,both,Least busy,Least busy,Fewest orders,10
56,2550362,1,prior,10,4,8,30.0,35951,7,0,35955.0,Organic Unsweetened Almond Milk,91.0,16.0,1.3,both,Least busy,Least busy,Fewest orders,10
57,2550362,1,prior,10,4,8,30.0,13032,8,1,13032.0,Cinnamon Toast Crunch,121.0,14.0,4.0,both,Least busy,Least busy,Fewest orders,10
58,2550362,1,prior,10,4,8,30.0,12427,9,1,12427.0,Original Beef Jerky,23.0,19.0,4.4,both,Least busy,Least busy,Fewest orders,10
59,2168274,2,prior,1,2,11,NaN,32792,1,0,32794.0,Chipotle Beef & Pork Realstick,23.0,19.0,5.2,both,Regularly busy,Regularly busy,Fewest orders,14
60,2168274,2,prior,1,2,11,NaN,47766,2,0,47770.0,Organic Avocado,24.0,4.0,6.3,both,Regularly busy,Regularly busy,Fewest orders,14
61,2168274,2,prior,1,2,11,NaN,20574,3,0,20575.0,Roasted Turkey,96.0,20.0,2.3,both,Regularly busy,Regularly busy,Fewest orders,14
62,2168274,2,prior,1,2,11,NaN,12000,4,0,12000.0,Baked Organic Sea Salt Crunchy Pea Snack,72.0,13.0,10.9,both,Regularly busy,Regularly busy,Fewest orders,14
63,2168274,2,prior,1,2,11,NaN,48110,5,0,48114.0,Thin Stackers Brown Rice Lightly Salted,78.0,19.0,2.7,both,Regularly busy,Regularly busy,Fewest orders,14
64,2168274,2,prior,1,2,11,NaN,22474,6,0,22475.0,Cheddar Bunnies Snack Crackers,78.0,19.0,4.1,both,Regularly busy,Regularly busy,Fewest orders,14
65,2168274,2,prior,1,2,11,NaN,16589,7,0,16589.0,Plantain Chips,107.0,19.0,5.0,both,Regularly busy,Regularly busy,Fewest orders,14
66,2168274,2,prior,1,2,11,NaN,35917,8,0,35921.0,Organic Just Concord Grape Juice,98.0,7.0,9.4,both,Regularly busy,Regularly busy,Fewest orders,14
67,2168274,2,prior,1,2,11,NaN,27344,9,0,27346.0,Uncured Genoa Salami,96.0,20.0,14.8,both,Regularly busy,Regularly busy,Fewest orders,14
68,2168274,2,prior,1,2,11,NaN,30489,10,0,30491.0,Original Hummus,67.0,20.0,7.5,both,Regularly busy,Regularly busy,Fewest orders,14
69,2168274,2,prior,1,2,11,NaN,27966,11,0,27968.0,Organic Raspberries,123.0,4.0,4.4,both,Regularly busy,Regularly busy,Fewest orders,14
70,2168274,2,prior,1,2,11,NaN,13176,12,0,13176.0,Bag of Organic Bananas,24.0,4.0,10.3,both,Regularly busy,Regularly busy,Fewest orders,14
71,2168274,2,prior,1,2,11,NaN,45066,13,0,45070.0,Honeycrisp Apple,24.0,4.0,2.5,both,Regularly busy,Regularly busy,Fewest orders,14
72,1501582,2,prior,2,5,10,10.0,16797,1,0,16797.0,Strawberries,24.0,4.0,1.3,both,Regularly busy,Regularly busy,Fewest orders,14
73,1501582,2,prior,2,5,10,10.0,47526,2,0,47530.0,Goat Cheese Log,21.0,16.0,2.0,both,Regularly busy,Regularly busy,Fewest orders,14
74,1501582,2,prior,2,5,10,10.0,8479,3,0,8479.0,Original Black Box Tablewater Cracker,78.0,19.0,3.5,both,Regularly busy,Regularly busy,Fewest orders,14
75,1501582,2,prior,2,5,10,10.0,47766,4,1,47770.0,Organic Avocado,24.0,4.0,6.3,both,Regularly busy,Regularly busy,Fewest orders,14
76,1501582,2,prior,2,5,10,10.0,19051,5,0,19052.0,"Pita Chips, Simply Naked, Party Size",107.0,19.0,3.9,both,Regularly busy,Regularly busy,Fewest orders,14
77,1501582,2,prior,2,5,10,10.0,8138,6,0,8138.0,Traditional Hummus,67.0,20.0,2.0,both,Regularly busy,Regularly busy,Fewest orders,14
78,1901567,2,prior,3,1,10,3.0,47766,1,1,47770.0,Organic Avocado,24.0,4.0,6.3,both,Regularly busy,Regularly busy,Fewest orders,14
79,1901567,2,prior,3,1,10,3.0,32792,2,1,32794.0,Chipotle Beef & Pork Realstick,23.0,19.0,5.2,both,Regularly busy,Regularly busy,Fewest orders,14
80,1901567,2,prior,3,1,10,3.0,20574,3,1,20575.0,Roasted Turkey,96.0,20.0,2.3,both,Regularly busy,Regularly busy,Fewest orders,14
81,1901567,2,prior,3,1,10,3.0,7781,4,0,7781.0,Organic Sticks Low Moisture Part Skim Mozzarel...,21.0,16.0,6.6,both,Regularly busy,Regularly busy,Fewest orders,14
82,1901567,2,prior,3,1,10,3.0,28874,5,0,28876.0,Carrot Ginger Soup,1.0,20.0,6.2,both,Regularly busy,Regularly busy,Fewest orders,14
83,738281,2,prior,4,2,10,8.0,49451,1,0,49455.0,Artichoke Spinach Dip,67.0,20.0,7.1,both,Regularly busy,Regularly busy,Fewest orders,14
84,738281,2,prior,4,2,10,8.0,32792,2,1,32794.0,Chipotle Beef & Pork Realstick,23.0,19.0,5.2,both,Regularly busy,Regularly busy,Fewest orders,14
85,738281,2,prior,4,2,10,8.0,32139,3,0,32141.0,Hommus Classic Original,67.0,20.0,7.5,both,Regularly busy,Regularly busy,Fewest orders,14
86,738281,2,prior,4,2,10,8.0,34688,4,0,34690.0,Good Belly Probiotics Juice Drink Blueberry Ac...,31.0,7.0,5.8,both,Regularly busy,Regularly busy,Fewest orders,14
87,738281,2,prior,4,2,10,8.0,36735,5,0,36739.0,Organic Roasted Sliced Chicken Breast,96.0,20.0,8.9,both,Regularly busy,Regularly busy,Fewest orders,14
88,738281,2,prior,4,2,10,8.0,37646,6,0,37650.0,Organic Gala Apples,24.0,4.0,9.1,both,Regularly busy,Regularly busy,Fewest orders,14
89,738281,2,prior,4,2,10,8.0,22829,7,0,22830.0,Multigrain Flax Seeded Flatbread Crackers,78.0,19.0,5.5,both,Regularly busy,Regularly busy,Fewest orders,14
90,738281,2,prior,4,2,10,8.0,24852,8,0,24853.0,Banana,24.0,4.0,12.3,both,Regularly busy,Regularly busy,Fewest orders,14
91,738281,2,prior,4,2,10,8.0,47209,9,0,47213.0,Organic Hass Avocado,24.0,4.0,4.0,both,Regularly busy,Regularly busy,Fewest orders,14
92,738281,2,prior,4,2,10,8.0,33276,10,0,33278.0,Kalamata Olive Spread,67.0,20.0,10.8,both,Regularly busy,Regularly busy,Fewest orders,14
93,738281,2,prior,4,2,10,8.0,45613,11,0,45617.0,Pad Thai,38.0,1.0,12.6,both,Regularly busy,Regularly busy,Fewest orders,14
94,738281,2,prior,4,2,10,8.0,9681,12,0,9681.0,Chicken Tikka Masala with Cumin Infused Basmat...,38.0,1.0,2.0,both,Regularly busy,Regularly busy,Fewest orders,14
95,738281,2,prior,4,2,10,8.0,21150,13,0,21151.0,Fire Grilled Steak Bowl,38.0,1.0,5.9,both,Regularly busy,Regularly busy,Fewest orders,14
96,1673511,2,prior,5,3,11,8.0,47144,1,0,47148.0,Unsweetened Original Almond Breeze Almond Milk,91.0,16.0,14.0,both,Regularly busy,Regularly busy,Fewest orders,14
97,1673511,2,prior,5,3,11,8.0,5322,2,0,5322.0,Gluten Free Dark Chocolate Chunk Chewy with a ...,3.0,19.0,2.9,both,Regularly busy,Regularly busy,Fewest orders,14
98,1673511,2,prior,5,3,11,8.0,17224,3,0,17224.0,Oats & Honey Gluten Free Granola,3.0,19.0,1.6,both,Regularly busy,Regularly busy,Fewest orders,14
99,1673511,2,prior,5,3,11,8.0,38656,4,0,38660.0,Gluten Free Peanut Butter Dark Chocolate Chewy...,3.0,19.0,3.4,both,Regularly busy,Regularly busy,Fewest orders,14

6 Deriving Columns with loc()

In [46]:
df_ords_prods_merge.loc[df_ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [48]:
df_ords_prods_merge.loc[(df_ords_prods_merge['max_order'] <= 40) & (df_ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [50]:
df_ords_prods_merge.loc[df_ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [54]:
df_ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

loyalty_flag
Regular customer    15891507
Loyal customer      10294027
New customer         6249525
Name: count, dtype: int64

In [56]:
df_ords_prods_merge[['user_id', 'loyalty_flag', 'order_number']].head(60)

    user_id      loyalty_flag  order_number
0         1      New customer             1
1         1      New customer             1
2         1      New customer             1
3         1      New customer             1
4         1      New customer             1
5         1      New customer             2
6         1      New customer             2
7         1      New customer             2
8         1      New customer             2
9         1      New customer             2
10        1      New customer             2
11        1      New customer             3
12        1      New customer             3
13        1      New customer             3
14        1      New customer             3
15        1      New customer             3
16        1      New customer             4
17        1      New customer             4
18        1      New customer             4
19        1      New customer             4
20        1      New customer             4
21        1      New customer             5
22        1      New customer             5
23        1      New customer             5
24        1      New customer             5
25        1      New customer             5
26        1      New customer             5
27        1      New customer             5
28        1      New customer             5
29        1      New customer             6
30        1      New customer             6
31        1      New customer             6
32        1      New customer             6
33        1      New customer             7
34        1      New customer             7
35        1      New customer             7
36        1      New customer             7
37        1      New customer             7
38        1      New customer             8
39        1      New customer             8
40        1      New customer             8
41        1      New customer             8
42        1      New customer             8
43        1      New customer             8
44        1      New customer             9
45        1      New customer             9
46        1      New customer             9
47        1      New customer             9
48        1      New customer             9
49        1      New customer             9
50        1      New customer            10
51        1      New customer            10
52        1      New customer            10
53        1      New customer            10
54        1      New customer            10
55        1      New customer            10
56        1      New customer            10
57        1      New customer            10
58        1      New customer            10
59        2  Regular customer             1

In [11]:
df_ords_prods_merge.shape

NameError: name 'df_ords_prods_merge' is not defined

7. Export Data

In [9]:
df_ords_prods_merge.to_pickle(os.path.join(path, 'df_ords_prods_merge_12_11.pkl'))

NameError: name 'df_ords_prods_merge' is not defined